### ISSUE TITLE
[Bug] CLI: "Error: ENOENT" if used via npm install -g under MacOS/Linux

### ISSUE THREAD

**Issue by ealap** [microsoft/accessibility-insights-service#1442] opened 2021-05-27 08:11 UTC
## Describe the bug

Unable to use ai-scan in WSL environment

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service
- [x] CLI

## To Reproduce

Environment:
OS: Windows 10 21H1 (OS Build 19043.1023)
Shell: WSL (Debian 10)
Node: v14.17.0
NPM: 7.14.0

1. Run 'ai-scan'
```
ai-scan --url "https://github.com"
```

## Expected behavior

AI scan will start

## Log files

```
node:internal/fs/utils:343
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/home/ealap/.nvm/versions/node/v16.2.0/lib-commonjs/node_modules/accessibility-insights-scan/node_modules/@uifabric/styling/lib-commonjs/index.js'
    at Object.openSync (node:fs:583:3)
    at Object.readFileSync (node:fs:451:35)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1136:18)
    at Module.load (node:internal/modules/cjs/loader:989:32)
    at Function.Module._load (node:internal/modules/cjs/loader:829:14)
    at Module.require (node:internal/modules/cjs/loader:1013:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/ealap/.nvm/versions/node/v16.2.0/lib/node_modules/accessibility-insights-scan/node_modules/office-ui-fabric-react/lib-commonjs/Styling.js:5:22)
    at Module._compile (node:internal/modules/cjs/loader:1109:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1138:10) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/home/ealap/.nvm/versions/node/v16.2.0/lib-commonjs/node_modules/accessibility-insights-scan/node_modules/@uifabric/styling/lib-commonjs/index.js'
}
```

**Comment by dbjorge** [comment] 2021-05-27 18:56
Thanks for the report!

You mention in the body of your issue that you're using node v14.17.0, but the error message in the log you included suggests that you're actually using node v16.20.0, so I've attempted a repro using both.

Based on the paths in the error message, it appears that the node version is unimportant, but it does appear important that you're using a global install of ai-scan (eg, `npm install -g accessibility-insights-scan`, rather than `npx ai-scan` from within a project with a `package.json` dependency on `accessibility-insights-scan`). The combination of a global install and a Linux/MacOS environment seems to be the key to reproducing this; I was able to reproduce the issue in each of the following environments:

* Global install, WSL/Debian 10, Node v14.17.0
* Global install, WSL/Debian 10, Node v16.2.0
* Global install, WSL/Ubuntu 18.04, Node v14.17.0
* Global install, WSL/Ubuntu 18.04, Node v16.2.0
* Global install, MacOS 11.2, Node v14.17.0
* Global install, MacOS 11.2, Node v16.2.0

I was **not** able to repo in any of the following environments:

* Global install, Windows, Node v14.17.0
* Global install, Windows, Node v16.2.0
* Local install, WSL/Debian 10, Node v14.17.0
* Local install, WSL/Debian 10, Node v16.2.0
* Local install, WSL/Ubuntu 18.04, Node v14.17.0
* Local install, MacOS 11.2, Node v14.17.0
* Local install, Windows, Node v14.17.0

Starting an actual scan isn't necessary; in the cases where it repros, `ai-scan --help` is sufficient.

I'm going to retitle the issue slightly based on these symptoms. Since it's reproducible, I think we have enough information to proceed from.

As a workaround until we're able to release a fix for this, you can try it with a non-global install of the package:

```bash
> mkdir ai-scan-testing
> npm init -y
> npm install accessibility-insights-scan
> npx ai-scan --help
```

**Comment by dbjorge** [comment] 2021-05-27 19:18
In addition to the reported error case, I found that even in the working environments, scanning against `https://github.com` specifically fails with an unactionable error message where scanning against other sites, like `https://accessibilityinsights.io`, `https://microsoft.com`, and `https://cnn.com` succeed. I've filed #1443 to track the unactionable error message against `https://github.com` (and a few other cases).

**Closed** 2021-06-01 17:44 UTC
Labels: bug, status: active
