### ISSUE TITLE
[Bug] CLI: Different result for same URL when you run AI-Scan for single url vs crawling

### ISSUE THREAD

**Issue by AhmedAbdoOrtiga** [microsoft/accessibility-insights-service#1285] opened 2021-02-11 02:09 UTC
## Describe the bug

We get a different result when you run ai-scan for single url vs when you run ai-scan with crawling for same url

## Area

- [ ] Install script
- [ ] Update script
- [ ] Service
- [x] CLI

## To Reproduce

- Run CLI on "https://www.microsoft.com/en-us/surface", you will see that there's no a11y issues.
- RUN CLI with crawling on the same URL "https://www.microsoft.com/en-us/surface", you will see that there's multiple a11y issues

## Expected behavior
Result should be the same and there's should be no a11y issues for the mentioned URL

## Screenshots
![image](https://user-images.githubusercontent.com/45858632/107595912-f4d38200-6bca-11eb-9b4c-ddb866f891dc.png)

**Comment by karanbirsingh** [comment] 2021-05-18 23:45
I was unable to reproduce this bug today. I tried package versions 0.7.2 (current) and 0.6.0 (published version at time of bug). It's possible that the website changed, or that Ortiga was working off an older version of the package. I checked with Fer and we'll close this for now.

**Closed by karanbirsingh** 2021-05-18 23:45 UTC
Labels: bug, status: needs investigation
